#!/bin/bash

sensitive="apikey|password|urUniqueID|BEGIN.+KEY|END.+KEY|ssh-rsa|ecdsa-sha2"
flags=$(git diff -U0 --no-ext-diff --staged | grep -E -i --count "$sensitive")
if [ "$flags" -ne "0" ]; then
   echo "WARNING! You are attempting to commit sensitive data from:"
   git diff --no-ext-diff --staged --name-only -i -G "$sensitive" | sed 's/^/\t* /'
   echo -e "\nPlease review and unstage relevant hunks of those files with"
   echo -e "\tgit reset --patch"
   echo -e "\nCommit using the '--no-verify' option to ignore this warning (not recommended)"
   git diff --no-ext-diff --staged | grep -E -i "$sensitive"
   exit 1 
fi
